const specializations = {
  "": { label: "..." },
  it: { label: "IT" },
  marketing: { label: "Marketing" },
  finance: { label: "Finance" },
  healthcare: { label: "Healthcare" },
  engineering: { label: "Engineering" },
  design: { label: "Design" },
  education: { label: "Education" },
  hospitality: { label: "Hospitality" },
  legal: { label: "Legal" },
  sales: { label: "Sales" },
  humanResources: { label: "Human Resources" },
  logistics: { label: "Logistics" },
  researchAndDevelopment: { label: "Research and Development" },
  customerService: { label: "Customer Service" },
  operations: { label: "Operations" },
  accounting: { label: "Accounting" },
  realEstate: { label: "Real Estate" },
  telecommunications: { label: "Telecommunications" },
  mediaAndEntertainment: { label: "Media and Entertainment" },
  agriculture: { label: "Agriculture" },
  fashion: { label: "Fashion" },
  energy: { label: "Energy" },
  consulting: { label: "Consulting" },
  nonProfit: { label: "Non-Profit" },
  research: { label: "Research" },
  sports: { label: "Sports" },
  government: { label: "Government" },
  transportation: { label: "Transportation" },
  automotive: { label: "Automotive" },
  architecture: { label: "Architecture" },
  insurance: { label: "Insurance" },
  science: { label: "Science" },
  retail: { label: "Retail" },
  entrepreneurship: { label: "Entrepreneurship" },
  pharmaceutical: { label: "Pharmaceutical" },
  artAndDesign: { label: "Art and Design" },
  military: { label: "Military" },
  languageServices: { label: "Language Services" },
  cybersecurity: { label: "Cybersecurity" },
  business: { label: "Business" },
  other: { label: "Other" },
};

export default specializations;
